services:
  - type: web
    name: go-api-explorer
    env: go
    plan: free
    buildCommand: |
      if [ ! -f go.mod ]; then
        go mod init app
      fi
      go mod tidy
      go build -o app .
    startCommand: ./app
